name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: .github/workflows/middleman.yaml@main
    with:
      middleman-environment: transactionalblog
    secrets: inherit

  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: LS
      run: ls

    - name: Push to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
