name: middleman

on:
  push

jobs:
  middleman:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'

    - name: Install Node Packages
      run: npm install

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Graphviz
      run: sudo apt-get install -qq graphviz
    - name: Install Pikchr
      run: |
        wget https://pikchr.org/home/tarball/trunk/pikchr.tgz
        tar -xf pikchr.tgz
        cd pikchr
        make
        echo "$(pwd)" >> $GITHUB_PATH
    - name: Install dbdiag
      run: |
        curl https://raw.githubusercontent.com/thisismiller/dbdiag/main/ophistory.py -o ophistory
        chmod +x ophistory
    - name: ls
      run: |
        pwd
        ls

    - name: Build Middleman
      run: bundle exec middleman build --verbose --environment=transactionalblog

    - name: Push to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

