name: middleman

on:
  workflow_call:
    inputs:
      middleman-environment:
        required: true
        type: string

jobs:
  middleman:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'

    - name: Install Node Packages
      run: npm install

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Graphviz
      run: sudo apt-get install -qq graphviz
    - name: Install Pikchr
      run: |
        wget https://pikchr.org/home/tarball/trunk/pikchr.tgz
        tar -xf pikchr.tgz
        cd pikchr
        make
        echo "$(pwd)" >> $GITHUB_PATH
    - name: Install dbdiag
      run: |
        mkdir dbdiag
        curl https://raw.githubusercontent.com/thisismiller/dbdiag/main/ophistory.py -o dbdiag/ophistory
        cd dbdiag
        chmod +x ophistory
        echo "$(pwd)" >> $GITHUB_PATH

    - name: Build Middleman
      run: bundle exec middleman build --verbose --environment=${{ inputs.middleman-environment }}

